#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

/**
 * Measures what a response costs a model with API Pilot versus without, and
 * writes the result into README.md between the COST markers.
 *
 * The claim in ADR-0002 is that digest-plus-drill-down is cheaper than handing
 * a model the body, by enough of a margin that the whole design follows from it.
 * A number in a README that nobody can reproduce is marketing, so this is a
 * script over the built package, with fixtures generated deterministically here
 * rather than read from disk. Run it and you get the same table.
 *
 * Tokens are estimated at 4 bytes each — the same convention as
 * tests/golden/mcp-tools.test.ts, which explains why: there is no tokenizer in
 * this repo, adding a model-specific one for a comparison whose margin is two
 * orders of magnitude would be a dependency bought for nothing, and the estimate
 * is conservative for JSON, which tokenizes worse than prose.
 *
 * Usage:
 *   node scripts/token-cost.mjs           # rewrite the README table
 *   node scripts/token-cost.mjs --check   # fail if it would change
 */

const { digest } = await import(pathToUrl("dist/core/digest/digest.js"));
const { inspect } = await import(pathToUrl("dist/core/inspect/inspect.js"));

const README = join(process.cwd(), "README.md");
const BEGIN = "<!-- BEGIN COST: generated by scripts/token-cost.mjs -->";
const END = "<!-- END COST -->";

/** 4 bytes per token. See the header. */
const BYTES_PER_TOKEN = 4;

const encoder = new TextEncoder();

function pathToUrl(relative) {
  return new URL(`../${relative}`, import.meta.url).href;
}

function response(value) {
  const body = encoder.encode(JSON.stringify(value));
  return {
    status: 200,
    statusText: "OK",
    headers: [
      { name: "content-type", value: "application/json" },
      { name: "content-length", value: String(body.byteLength) },
    ],
    body,
    bodyTruncated: false,
    url: "https://api.example.test/resource",
    redirects: [],
    method: "GET",
    durationMs: 42,
    attempts: 1,
  };
}

/**
 * Deterministic, and shaped like the payloads that actually blow up a context
 * window: long lists of uniform records, and one deeply nested object.
 */
const CASES = [
  {
    name: "7,000-item user list",
    response: response(
      Array.from({ length: 7000 }, (_, i) => ({
        id: i + 1,
        name: `User ${i + 1}`,
        email: `user${i + 1}@example.test`,
        active: i % 3 !== 0,
        tags: ["alpha", "beta"],
        meta: { createdAt: "2026-01-01T00:00:00Z", score: (i % 100) / 10 },
      })),
    ),
    // What a model asks next: one record, to learn the real field values.
    path: "[0]",
  },
  {
    name: "paginated invoice page",
    response: response({
      object: "list",
      has_more: true,
      next_cursor: "cus_00000000000042",
      data: Array.from({ length: 100 }, (_, i) => ({
        id: `in_${String(i).padStart(14, "0")}`,
        amount_due: 1000 + i,
        currency: "usd",
        status: i % 4 === 0 ? "open" : "paid",
        customer: { id: `cus_${String(i).padStart(14, "0")}`, email: `a${i}@example.test` },
        lines: Array.from({ length: 3 }, (_, j) => ({
          id: `il_${i}_${j}`,
          description: `Seat licence, tier ${j + 1}`,
          amount: 250 * (j + 1),
        })),
      })),
    }),
    path: "data[0].lines",
  },
  {
    name: "single deeply nested resource",
    response: response({
      id: "sub_00000000000001",
      status: "active",
      customer: { id: "cus_00000000000001", email: "ops@example.test" },
      items: Array.from({ length: 12 }, (_, i) => ({
        id: `si_${i}`,
        price: { id: `price_${i}`, unit_amount: 900 + i, recurring: { interval: "month" } },
        quantity: i + 1,
      })),
      metadata: Object.fromEntries(
        Array.from({ length: 20 }, (_, i) => [`field_${i}`, `value ${i}`]),
      ),
    }),
    path: "items[0].price",
  },
  {
    name: "error envelope",
    response: response({
      error: {
        type: "invalid_request_error",
        code: "parameter_missing",
        message: "Missing required param: customer.",
        param: "customer",
        doc_url: "https://example.test/docs/error-codes/parameter_missing",
      },
    }),
    path: "error.code",
  },
];

function tokens(bytes) {
  return Math.ceil(bytes / BYTES_PER_TOKEN);
}

function measure({ name, response: httpResponse, path }) {
  const raw = httpResponse.body.byteLength;
  const summary = digest(httpResponse, { handle: "r_example0001" });
  const drilled = inspect({ headers: httpResponse.headers, body: httpResponse.body }, { path });

  // What the model actually pays for the two-step: the digest it always sees,
  // plus the one follow-up slice it asked for.
  const withPilot = summary.textBytes + encoder.encode(drilled.text).byteLength;

  return {
    name,
    path,
    raw,
    digestBytes: summary.textBytes,
    withPilot,
    ratio: withPilot / raw,
  };
}

function table(rows) {
  const format = new Intl.NumberFormat("en-US");
  const lines = [
    "| Response | Raw body | Digest | Digest + one `inspect` | Cost vs. raw |",
    "|---|---|---|---|---|",
  ];

  for (const row of rows) {
    const cells = [
      row.name,
      `${format.format(row.raw)} B — ~${format.format(tokens(row.raw))} tok`,
      `${format.format(row.digestBytes)} B — ~${format.format(tokens(row.digestBytes))} tok`,
      `${format.format(row.withPilot)} B — ~${format.format(tokens(row.withPilot))} tok`,
      `**${(row.ratio * 100).toFixed(2)}%**`,
    ];
    lines.push(`| ${cells.join(" | ")} |`);
  }

  return lines.join("\n");
}

const rows = CASES.map(measure);

const section = [
  BEGIN,
  "",
  table(rows),
  "",
  "The `inspect` column is the realistic sequence, not the flattering one: the",
  "digest the model always sees **plus** the one follow-up query it makes",
  `(\`${CASES[0].path}\`, \`${CASES[1].path}\`, \`${CASES[2].path}\`, \`${CASES[3].path}\` respectively).`,
  "Tokens are estimated at 4 bytes each, which is conservative for JSON.",
  "",
  "**The last two rows cost more than the raw body, and that is the honest shape",
  "of it.** A digest carries fixed overhead — status, handle, inferred shape — so",
  "on a response already small enough to paste it loses. The bet was never that",
  "digesting always wins; it is that the payloads which actually threaten a",
  "context window are large and uniform, and there the margin is three orders of",
  "magnitude. Nothing here caps how badly a small response can lose, because the",
  "absolute numbers are tens of tokens.",
  "",
  "Reproduce it with `pnpm run build && pnpm run cost`.",
  END,
].join("\n");

const current = await readFile(README, "utf8");
const start = current.indexOf(BEGIN);
const finish = current.indexOf(END);

if (start === -1 || finish === -1) {
  process.stderr.write(`README.md is missing the ${BEGIN} / ${END} markers.\n`);
  process.exit(1);
}

const updated = current.slice(0, start) + section + current.slice(finish + END.length);

if (process.argv.includes("--check")) {
  if (updated !== current) {
    process.stderr.write(
      "README.md token-cost table is out of date.\nRun `pnpm run cost` and commit the result.\n",
    );
    process.exit(1);
  }
  process.stdout.write("README.md token-cost table is up to date.\n");
} else {
  await writeFile(README, updated, "utf8");
  process.stdout.write(`Updated the token-cost table in ${README}\n`);
}
